/** Sprint 3.9 — faithful backend port of `prototype/index.html`'s `buildAnalysisPayload()` +
 * `freshSourceResultToSnapshot()` + `filterSourceSnapshotsToAsset()` + `summarizeNewsSnapshot()`
 * (Sprint 3.2B / 3.1B.2). This is now the ONE AnalysisPayload builder — Manual and Scheduled both
 * call it via `analysisEngine.ts`, never a second implementation (Section 1/5). */
import { randomUUID } from 'node:crypto';
import type { SourceKey, SourceResult } from '../types.js';
import { runNewsPipeline } from './newsPipeline.js';
import { SOURCE_LABELS } from './weightDefs.js';
import type { AnalysisEvidenceInput, AnalysisPayload, AnalysisPositionContext, SourceSnapshot } from './types.js';

/** Sprint 3.1B.2 Task 6 — these 3 sources list one `values` row per tracked symbol; a single-asset
 * analysis has no use for the other assets' rows (pure prompt-size bloat otherwise). */
const ASSET_SPECIFIC_SOURCE_KEYS: SourceKey[] = ['market', 'technical', 'derivatives'];

export function freshSourceResultToSnapshot(key: SourceKey, result: SourceResult): SourceSnapshot {
  const status: 'available' | 'partial' = result.status === 'stub' ? 'partial' : 'available';
  const values = (result.itemsRaw || []).map((it) => ({ label: it.label, value: it.value }));
  return {
    id: key, name: SOURCE_LABELS[key] || key, status,
    updatedAt: new Date(result.fetchedAt || Date.now()).toISOString(),
    values, summary: result.note || undefined, error: null,
  };
}

function filterSourceSnapshotsToAsset(sourceSnapshots: SourceSnapshot[], selectedAssetSymbol: string): void {
  sourceSnapshots.forEach((s) => {
    if (!ASSET_SPECIFIC_SOURCE_KEYS.includes(s.id)) return;
    s.values = (s.values || []).filter((v) => typeof v.label === 'string' && v.label.startsWith(selectedAssetSymbol));
  });
}

function summarizeNewsSnapshot(sourceSnapshots: SourceSnapshot[], newsPipelineStats: { fetchedCount: number; filteredCount: number; clusteredCount: number; selectedCount: number }): void {
  const newsSnap = sourceSnapshots.find((s) => s.id === 'news');
  if (!newsSnap) return;
  newsSnap.values = [
    { label: '已抓取新闻总数', value: String(newsPipelineStats.fetchedCount) },
    { label: '时间/资产筛选后', value: String(newsPipelineStats.filteredCount) },
    { label: '聚类后事件数', value: String(newsPipelineStats.clusteredCount) },
    { label: '已选入 selectedNewsEvents', value: String(newsPipelineStats.selectedCount) },
  ];
}

export function genAnalysisId(): string {
  return 'A' + Date.now().toString(36).toUpperCase() + randomUUID().replace(/-/g, '').slice(0, 4).toUpperCase();
}
export const CURRENT_PAYLOAD_VERSION = '1.2.0'; // Sprint 3.9: additive positionContext field, see analysis/types.ts

export interface BuildAnalysisPayloadInput {
  symbol: string;
  timeframe: string;
  dateRange: string;
  sourceWeights: Record<string, number>;
  additionalEvidence: AnalysisEvidenceInput[];
  /** Real SourceResult per required (weight > 0) source key, already fetched (Section 8: no
   * partial-input analysis — the caller guarantees every required key is present here). */
  sourceResults: Partial<Record<SourceKey, SourceResult>>;
  positionContext: AnalysisPositionContext | null;
  /** Sprint 3.9.1.1, Section 21 — pre-generated by the caller (`analysisEngine.ts#runAnalysis`,
   * itself given it by whoever created the AnalysisRun) so the SAME id exists from the very start of
   * the run, before any snapshot work — not invented here anymore. Falls back to `genAnalysisId()`
   * only when omitted, so any direct test caller of `buildAnalysisPayload()` keeps working unchanged. */
  analysisId?: string;
}

export function buildAnalysisPayload(input: BuildAnalysisPayloadInput): AnalysisPayload {
  const sourceSnapshots: SourceSnapshot[] = Object.entries(input.sourceResults).map(([key, result]) => freshSourceResultToSnapshot(key as SourceKey, result as SourceResult));
  const newsResult = input.sourceResults.news;
  const pipeline = runNewsPipeline(input.symbol, input.dateRange, newsResult?.itemsRaw || []);
  filterSourceSnapshotsToAsset(sourceSnapshots, input.symbol);
  summarizeNewsSnapshot(sourceSnapshots, pipeline.stats);

  const additionalEvidence = input.additionalEvidence.map((ev) => {
    const item: AnalysisEvidenceInput = { id: ev.id, type: ev.type, title: ev.title, content: ev.content, reference: ev.reference, weight: Number(ev.weight) };
    if (ev.parsedContent) item.parsedContent = ev.parsedContent;
    return item;
  });

  return {
    analysisId: input.analysisId || genAnalysisId(),
    createdAt: new Date().toISOString(),
    payloadVersion: CURRENT_PAYLOAD_VERSION,
    symbol: input.symbol, timeframe: input.timeframe, dateRange: input.dateRange,
    sourceWeights: input.sourceWeights, additionalEvidence, sourceSnapshots,
    selectedNewsEvents: pipeline.selectedEvents,
    // Section 8 — no partial analysis: every required source already succeeded (with retry) before
    // this function is ever called, so these three are always [] here, kept only for shape
    // compatibility with ANALYSIS_PAYLOAD_SPEC.md (same rationale as the original frontend builder).
    dataQuality: {
      unavailableSources: sourceSnapshots.filter((s) => (s.status as string) === 'unavailable').map((s) => s.id),
      partialSources: sourceSnapshots.filter((s) => s.status === 'partial').map((s) => s.id),
      staleSources: [],
    },
    positionContext: input.positionContext,
  };
}
